### ISSUE TITLE
See list of all open issues

### ISSUE THREAD

**Issue by mattbisbee** [mattbisbee/git-it-done#2]
**Description**

  - Users can click on a repository name, which will route them to a new page.

  - The second HTML page will display a list of all open issues for that repository.

**Comment by danishbansal808** [comment]
Hi, @mattbisbee I would like to know more information about the feature you want to add.

**Comment by mattbisbee** [comment]
I’m actually learning through a Bootcamp so it’s not an actual app, just a learning exercise. Thanks anyway
